name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run build script
      run: ./build.sh
      
    - name: Upload production build
      uses: actions/upload-artifact@v3
      with:
        name: AntScuttle
        path: antscuttle-1.0-all.jar


  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run test script
      run: ./test.sh
